spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 900000

UserResource:
  signin: Autentica o usuario e retorna o JWT Token
  signup: Cria o usuario e retorna o JWT Token
  search: Retorna um usuario especifico pelo username
  me: Retorna os dados atuais do usuario

TaskResource:
  listTasks: Retorna as tarefas não concluidas e filtra pela prioridade
  insert: Insere uma tarefa
  update: Atualiza uma tarefa
  updateStatus: Atualiza o status de conclusao de uma tarefa
  delete: Deleta uma tarefa